server:
  port: 8082
  # 指定项目名
  #servlet:
  #context-path: /test
  tomcat:
    max-connections: 10000
    max-threads: 10000
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bmw_seckill?useSSL=true&charset=utf8mb4&serverTimezone=Hongkong
    username: root
    password: wxm147369
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:  # Redis数据库索引（默认为0）
    database: '0'
    host: 127.0.0.1  #Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password:
    jedis:
      pool:
        max-active: 10000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10000 # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接
    timeout: 10000 # 连接超时时间（毫秒）
  mvc:
    view:
      prefix: /WEB-INF/page/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.bmw.seckill.model
token:
  expire:
    seconds: 2592000 # 30*24*60*60*1000 = 2,592,000